import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-blog-list',
  templateUrl: './blog-list.component.html',
  styleUrls: ['./blog-list.component.scss']
})
export class BlogListComponent {

  private POSTS = [
    { icon: 'https://i.imgur.com/Cw7m2JK.png', username: 'megumingas', message: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis?' },
    { icon: 'https://i.imgur.com/Cw7m2JK.png', username: 'maschinenmann', message: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis?' },
    { icon: 'https://i.imgur.com/Cw7m2JK.png', username: 'megumingas', message: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis?' },
    { icon: 'https://i.imgur.com/Cw7m2JK.png', username: 'maschinenmann', message: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis?' },
    { icon: 'https://i.imgur.com/Cw7m2JK.png', username: 'megumingas', message: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis?' },
    { icon: 'https://i.imgur.com/Cw7m2JK.png', username: 'maschinenmann', message: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis?' },
    { icon: 'https://i.imgur.com/Cw7m2JK.png', username: 'megumingas', message: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis?' },
    { icon: 'https://i.imgur.com/Cw7m2JK.png', username: 'megumingas', message: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, aliquam! Sint numquam cumque praesentium eligendi velit iure tempore. Ducimus illo non odit aperiam perspiciatis minima corporis rerum eius pariatur reiciendis?' },
  ];

  constructor() { }

  public get posts() {
    return this.POSTS;
  }

}
